In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_csv("/content/drive/MyDrive/Innovative Skills/NLP/IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.columns

Index(['review', 'sentiment'], dtype='object')

#Mini-EDA

In [5]:
df["review"].sample(5)

5787     Our Family and friends enjoyed this movie very...
20733    It's hard for me to assign the "fair" number o...
8956     Okay, I was bored and decided to see this movi...
34816    Being too young to have experienced the Hammer...
38021    I loved this excellent movie. Farrah Fawcett p...
Name: review, dtype: object

In [ ]:
df["text_length"] = df["review"].apply(len)
df["text_length"].describe()

count    50000.000000
mean      1309.431020
std        989.728014
min         32.000000
25%        699.000000
50%        970.000000
75%       1590.250000
max      13704.000000
Name: text_length, dtype: float64

In [ ]:
df.head()

                                              review sentiment  text_length
0  One of the other reviewers has mentioned that ...  positive         1761
1  A wonderful little production. <br /><br />The...  positive          998
2  I thought this was a wonderful way to spend ti...  positive          926
3  Basically there's a family where a little boy ...  negative          748
4  Petter Mattei's "Love in the Time of Money" is...  positive         1317

In [ ]:
df["word_count"] = df["review"].apply(lambda x: len(x.split()))

df["word_count"]

0        307
1        162
2        166
3        138
4        230
        ...
49995    194
49996    112
49997    230
49998    212
49999    129
Name: word_count, Length: 50000, dtype: int64

In [ ]:
df.head()

,review,sentiment,text_length,word_count
0,One of the other reviewers has mentioned that ...,positive,1761,307
1,A wonderful little production. <br /><br />The...,positive,998,162
2,I thought this was a wonderful way to spend ti...,positive,926,166
3,Basically there's a family where a little boy ...,negative,748,138
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1317,230

In [ ]:
df.loc[df["word_count"].idxmax()]

review         Match 1: Tag Team Table Match Bubba Ray and Sp...
sentiment                                               positive
text_length                                                13704
word_count                                                  2470
Name: 31481, dtype: object

#Regex

In [6]:
import re

In [ ]:
# Pattern	          Meaning
# .	                Any character
# \d	              Digit (0–9)
# \w	              Word character
# \s	              Space
# +	                One or more
# *	                Zero or more
# []	              Character set
# ^	                NOT (inside brackets)

<p> </p>

<.*?>

In [21]:
text = "I LOVED this movie!!! https://movie.com 😍😍 01/1000000 , 20 Visit https://movie.com"
text

'I LOVED this movie!!! https://movie.com 😍😍 01/1000000 , 20 Visit https://movie.com'

In [ ]:
# re.findall
# search
# sub [Pattern , Replacement , Text]
# findall(pattern , Text)
#search(pattern , Text)

In [15]:
re.findall(r"\d+", text)

['01', '1000000', '20']

In [22]:
re.sub(r"http\S+", "", text)

'I LOVED this movie!!!  😍😍 01/1000000 , 20 Visit '

#Example 1

In [23]:
text = "Check this website https://example.com for details"
re.findall(r"http\S+", text)

['https://example.com']

#Example 2

In [24]:
text = "Visit http://abc.com now"
re.findall(r"http\S+", text)

['http://abc.com']

#Number Detection

In [25]:
re.sub(r"\d+", "", "Rating is 10/10")

'Rating is /'

#Punctuation

In [27]:
re.findall(r"[^\w\s]", "Amazing!!! 😍")

['!', '!', '!', '😍']

In [31]:
re.sub(r"[^\w\s]", "","Amazing#!!! 😍")

'Amazing '

#Removing Sapaces

In [34]:
re.sub(r"\s+", " ", "Too   many    spaces")

'Too many spaces'

In [44]:
text = "I LOVED this32 movie!!! 😍😍 Visit https://movie.com"

In [45]:
text = text.lower()

In [46]:
text = re.sub(r"http\S+", "", text)

In [47]:
text = re.sub(r"[^0-9a-z\s]", "", text) #Punctuation removal
text

'i loved this32 movie  visit '

In [48]:
text = re.sub(r"\s+", "X", "Hello Hey       I")

In [49]:
text

'HelloXHeyXI'

#Main Dataset

In [55]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+", "", text)
    text = re.sub(r"<.*?>", "", text) #HTML Tag Removal
    text = re.sub(r"[^a-z\s]", "", text)
    text = re.sub(r"\s+", " ", text)
    return text.strip()

df["clean_review"] = df["review"].apply(clean_text)
df[["review", "clean_review"]].head()

,review,clean_review
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,a wonderful little production the filming tech...
2,I thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,basically theres a family where a little boy j...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter matteis love in the time of money is a ...

In [ ]:
re.sub(r"\d+" , "" , "Hello 20/40")

'Hello /'

In [ ]:
df.head()

,review,sentiment,text_length,word_count,clean_review
0,One of the other reviewers has mentioned that ...,positive,1761,307,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,positive,998,162,a wonderful little production the filming tech...
2,I thought this was a wonderful way to spend ti...,positive,926,166,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,negative,748,138,basically theres a family where a little boy j...
4,"Petter Mattei's ""Love in the Time of Money"" is...",positive,1317,230,petter matteis love in the time of money is a ...

In [ ]:
df.loc[:, ["review", "clean_review"]]

,review,clean_review
0,One of the other reviewers has mentioned that ...,one of the other reviewers has mentioned that ...
1,A wonderful little production. <br /><br />The...,a wonderful little production the filming tech...
2,I thought this was a wonderful way to spend ti...,i thought this was a wonderful way to spend ti...
3,Basically there's a family where a little boy ...,basically theres a family where a little boy j...
4,"Petter Mattei's ""Love in the Time of Money"" is...",petter matteis love in the time of money is a ...
...,...,...
49995,I thought this movie did a down right good job...,i thought this movie did a down right good job...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",bad plot bad dialogue bad acting idiotic direc...
49997,I am a Catholic taught in parochial elementary...,i am a catholic taught in parochial elementary...
49998,I'm going to have to disagree with the previou...,im going to have to disagree with the previous...
49999,No one expects the Star Trek movies to be high...,no one expects the star trek movies to be high...